rbac: true
controller:
  apisvc:
    type: ClusterIP 
  replicas: 1
  federation:
    managedsvc:
      type: ClusterIP
  ranchersso:
    enabled: false
  env:
    - name: CTRL_EN_ICMP_POLICY
      value: "1"
  affinity: {}
  pvc:
    enabled: false 
manager:
  svc:
    type: ClusterIP 
  env:
    ssl: true
cve:
  scanner:
    replicas: 1
  adapter:
    enabled: true
crdwebhook:
  enabled: false
