apiVersion: v1
kind: Service
metadata:
  namespace: gotenberg
  creationTimestamp: null
  labels:
    app: gotenberg
  name: gotenberg
spec:
  ports:
  - name: gotenberg-svc
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: gotenberg
  type: ClusterIP
status:
  loadBalancer: {}
