---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: pixiedocs-http
  namespace: gotenberg
spec:
  hostnames:
  - "pixiedocs.rajesh-kumar.in"
  parentRefs:
  - name: common-server-gateway 
    namespace: common-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: pixiedocs 
      port: 80
