apiVersion: v1
kind: Service
metadata:
  namespace: gotenberg
  name: pixiedocs
  labels:
    app: pixiedocs
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: pixiedocs
