server:
  ha:
    enabled: false 
    replicas: 1
    raft:
      enabled: true
  dataStorage:
    enabled: true
    size: 10Gi
  affinity: null  # For easier testing environment
  ui:
    enabled: true
