providers:
  kubernetesGateway:
    enabled: true
gateway:
  listeners:
    websecure:
      namespacePolicy: "All"
      protocol: HTTPS
      port: 8443
      certificateRefs:
        - kind: Secret
          name: rajesh-tls-cert
          namespace: certificate-ns
      mode: Terminate
