---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: rancher-httproute
spec:
  hostnames:
  - "rancher.rajesh-kumar.in"
  parentRefs:
  - name: rancher-master-gateway 
    namespace: cilium-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: rancher-master-rancher-prime 
      port: 80

