apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
- ../../../base/external-dns

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --txt-owner-id=asus-cluster
    target:
      kind: Deployment
      name: external-dns
