rbac: true
controller:
  apisvc:
    type: ClusterIP 
  replicas: 1
  federation:
    managedsvc:
      type: ClusterIP
  ranchersso:
    enabled: true
  env:
    - name: CTRL_EN_ICMP_POLICY
      value: "1"
  affinity: {}
  pvc:
    enabled: false
    storageClass: longhorn
    capacity: 2Gi
cve:
  scanner:
    replicas: 2
