rbac: true
global:
  cattle:
    url: https://rancher.rajesh-kumar.in/ 
controller:
  nodeSelector: 
    beta.kubernetes.io/arch: amd64
  apisvc:
    type: ClusterIP 
  replicas: 1
  federation:
    managedsvc:
      type: ClusterIP
  ranchersso:
    enabled: true
  env:
    - name: CTRL_EN_ICMP_POLICY
      value: "1"
  affinity: {}
manager:
  svc:
    type: ClusterIP 
  env:
    ssl: true 
  ingress:
    enabled: true
    host: rajesh-nv.rajesh-kumar.com 
cve:
  scanner:
    replicas: 3
  adapter:
    enabled: true
crdwebhook:
  enabled: false
enforcer:
  env:
    - name: ENF_NO_SECRET_SCANS
      value: "1"
    - name: ENF_NETPOLICY_PULL_INTERVAL
      value: "60"
    - name: ENF_NO_AUTO_BENCHMARK
      value: "1"

