apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: common-server-gateway-tls-passthrough 
  namespace: common-gateway
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: TLS 
    port: 443
    name: tls-listener
    tls:
      mode: Passthrough
    allowedRoutes:
      namespaces:
        from: All

---
apiVersion: gateway.networking.k8s.io/v1alpha2 
kind: TLSRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  hostnames:
  - "argocd.rajesh-kumar.in"
  parentRefs:
  - name: common-server-gateway-tls-passthrough
    namespace: common-gateway 
  rules:
  - backendRefs:
    - name: argocd-server
      port: 443
