apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rajesh-tls-cert
  namespace: argo 
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: rajesh-tls-cert
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      engineVersion: v2
  data:
  - secretKey: tls.crt 
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: kv/rajesh-tls-cert
      metadataPolicy: None
      property: tls.cert
  - secretKey: tls.key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: kv/rajesh-tls-cert
      metadataPolicy: None
      property: tls.key
