apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      serviceAccountName: rancher-master-external-secrets 
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.15.1
        args:
        - --source=gateway-httproute
        - --source=gateway-tlsroute
        - --source=service
        - --domain-filter=rajesh-kumar.in
        - --provider=cloudfare
        - --zone-id-filter=96dd69c5ed5e262652233501b82b9593
        - --log-level=debug
        env:
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-key
              key: apiKey
        - name: CF_API_EMAIL
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-key
              key: email
