apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: cloudfare-secret 
  namespace: external-dns
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-key 
    creationPolicy: Owner
  data:
    - secretKey: apiKey
      remoteRef:
        key: kv/cloudflare-api-key
        property: apiKey
    - secretKey: email 
      remoteRef:
        key: kv/cloudflare-api-key
        property: email 
