apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: cloudflare-secret 
  namespace: cert-manager 
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token 
    creationPolicy: Owner
  data:
    - secretKey: apiKey
      remoteRef:
        key: kv/cloudflare-api-token
        property: apiKey
    - secretKey: email 
      remoteRef:
        key: kv/cloudflare-api-token
        property: email 
