apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: aws-roles-anywhere
  namespace: cert-manager 
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: aws-roles-anywhere
    creationPolicy: Owner
  data:
    - secretKey: client.crt
      remoteRef:
        key: kv/aws-roles-anywhere
        property: client.crt
    - secretKey: client.key
      remoteRef:
        key: kv/aws-roles-anywhere
        property: client.key
    - secretKey: profile-arn
      remoteRef:
        key: kv/aws-roles-anywhere
        property: profile-arn
    - secretKey: trust-anchor-arn
      remoteRef:
        key: kv/aws-roles-anywhere
        property: trust-anchor-arn
    - secretKey: role-arn
      remoteRef:
        key: kv/aws-roles-anywhere
        property: role-arn
    - secretKey: generate-aws-creds.sh
      remoteRef:
        key: kv/aws-roles-anywhere
        property: generate-aws-creds
    - secretKey: refresh-credentials.sh
      remoteRef:
        key: kv/aws-roles-anywhere
        property: refresh-credentials
