apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/gateway

patches:
  - patch: |-
      - op: add	
        path: /spec/listeners/0/tls 
        value:
          mode: Terminate
          certificateRefs:
            - name: rajesh-tls-cert
              namespace: certificate-ns
              kind: Secret 
      - op: add
        path: /spec/gatewayClassName
        value: cilium 
         
    target:
      kind: Gateway 
