rbac: true
global:
  cattle:
    url: https://rancher.rajesh-kumar.in/k8s/clusters/c-m-bx76dsgg 
controller:
  apisvc:
    type: ClusterIP 
  replicas: 1
  federation:
    managedsvc:
      type: ClusterIP
  ranchersso:
    enabled: true
  env:
    - name: CTRL_EN_ICMP_POLICY
      value: "1"
  affinity: {}
  pvc:
    enabled: false
    storageClass: longhorn
    capacity: 2Gi
manager:
  svc:
    type: ClusterIP 
  env:
    ssl: false 
cve:
  scanner:
    replicas: 1
  adapter:
    enabled: true
crdwebhook:
  enabled: false
enforcer:
  env:
    - name: ENF_NO_SECRET_SCANS
      value: "1"
    - name: ENF_NETPOLICY_PULL_INTERVAL
      value: "60"
    - name: ENF_NO_AUTO_BENCHMARK
      value: "1"

