apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vault-route
  namespace: vault
spec:
  hostnames:
  - vault.rajesh-kumar.in
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: rancher-server-gateway
    namespace: cilium-gateway
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: rancher-master-vault
      port: 8200
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
