apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-keys-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /var/lib/rancher/k3s/storage/vault-keys
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rajesh-rockylinux 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-keys
  namespace: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path  # Use local storage
  volumeName: vault-keys-pv 
