version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./api-service
    container_name: api-service
    ports:
      - "5000:5000"
      - "5001:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - PORT=5000
      - VERSION=v1
    depends_on:
      - mongo

  backend-v2:
    build:
      context: ./api-service
    container_name: api-service-v2
    ports:
      - "5002:5000"  # Expose as api-v2 on port 5002
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - PORT=5000
      - VERSION=v2  # Set version to v2
    depends_on:
      - mongo

  frontend:
    image: nginx:stable
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
      - backend-v2

volumes:
  mongo-data:
# docker-compose.yml
