controller:
  extraVolumes:
    - name: aws-roles-anywhere
      secret:
        secretName: aws-roles-anywhere
        defaultMode: 0400
    - name: shared-aws-credentials
      emptyDir: {}
    - name: generate-aws-creds-script
      secret:
        secretName: aws-roles-anywhere
        items:
        - key: generate-aws-creds.sh
          path: generate-aws-creds.sh
          defaultMode: 0500
    - name: aws-creds-refresh-script
      secret:
        secretName: aws-roles-anywhere
        items:
        - key: refresh-credentials.sh
          path: start-aws-credentials-refresh.sh
          defaultMode: 0500
  
  extraVolumeMounts:
    - name: shared-aws-credentials
      mountPath: /shared-aws-credentials
    
  # Add your custom environment variables
  extraEnvVars:
    - name: AWS_SHARED_CREDENTIALS_FILE
      value: /shared-aws-credentials/aws-credentials
    - name: AWS_DEFAULT_REGION
      value: ap-south-1
    - name: AWS_EC2_METADATA_DISABLED
      value: "true"

  # Add your init containers
  initContainers:
    - name: generate-aws-creds
      image: alpine:latest
      command:
      - "/bin/sh"
      - "-c"
      - "/bin/sh /scripts/generate-aws-creds.sh"
      env:
      - name: AWS_REGION
        value: ap-south-1
      volumeMounts:
      - name: generate-aws-creds-script
        mountPath: /scripts
      - name: aws-roles-anywhere
        mountPath: /etc/aws-roles-anywhere
      - name: shared-aws-credentials
        mountPath: /shared-aws-credentials

  # Add your sidecar containers
  sidecars:
    - name: aws-credentials-refresher
      image: alpine
      command:
      - "/bin/sh"
      - "-c"
      - "/bin/sh /script-aws/start-aws-credentials-refresh.sh"
      volumeMounts:
      - name: shared-aws-credentials
        mountPath: /shared-aws-credentials
        readOnly: false
      - name: generate-aws-creds-script
        mountPath: /scripts
      - name: aws-creds-refresh-script
        mountPath: /script-aws
      - name: aws-roles-anywhere
        mountPath: /etc/aws-roles-anywhere
    - name: debug
      image: busybox
      command: ["sh", "-c", "sleep infinity"]
      volumeMounts:
      - name: shared-aws-credentials
        mountPath: /shared-aws-credentials
