apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/neuvector-httproute
patches:
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
          - "nv-rke2.rajesh-kumar.in"
      - op: add
        path: /spec/parentRefs 
        value:
          - name: rke2-server-gateway
            namespace: istio-gateway
    target:
      kind: HTTPRoute
      name: neuvector-httproute
