apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend-access 
spec:
  provider:
    vault:
      server: "https://vault.rajesh-kumar.in"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "rancher-master"
          role: "cert-reader"
          serviceAccountRef:
            name: "rancher-master-external-secrets"
            audiences:
              - vault


---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-pusher
spec:
  provider:
    vault:
      server: "https://vault.rajesh-kumar.in"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "rancher-master"
          role: "cert-pusher"
          serviceAccountRef:
            name: "cert-pusher"
            audiences:
              - vault
