apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend-access 
spec:
  provider:
    vault:
      server: "https://vault.rajesh-kumar.in"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "rancher-master"
          role: "cert-push"
          serviceAccountRef:
            name: "external-secrets"
