
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: manifest-apps
  namespace: argo
spec:
  generators:
  - list:
      elements:
        - cluster: k3s-server 
          app-name: neuvector-httproute
          path: argocd/kustomize/overlays/k3s-server/neuvector-httproute
          namespace: cattle-system
        - cluster: k3s-server 
          app-name: neuvector-external-secret
          path: argocd/kustomize/overlays/k3s-server/neuvector-external-secret/
          namespace: cattle-neuvector-system
        - cluster: k3s-server 
          app-name: neuvector-configmaps
          path: argocd/kustomize/overlays/k3s-server/neuvector-configmaps/
          namespace: cattle-neuvector-system
        - cluster: k3s-server 
          app-name: istio-config
          path: argocd/kustomize/overlays/k3s-server/istio-config/
          namespace: istio-system
        - cluster: k3s-server 
          app-name: kiali-httproute
          path: argocd/kustomize/overlays/k3s-server/kiali-httproute/
          namespace: istio-system
       # - cluster: k3s-server 
       #   app-name: vault-cert-sync-job
       #   path: argocd/kustomize/overlays/k3s-server/vault-cert-sync-job/
       #   namespace: cert-manager
        - cluster: rancher-master 
          app-name: rancher-httproute
          path: argocd/kustomize/overlays/rancher-master/rancher-httproute
          namespace: cattle-system
        - cluster: rancher-master 
          app-name: cert-manager-config 
          path: argocd/kustomize/overlays/rancher-master/cert-manager-config
          namespace: cert-manager
        - cluster: rancher-master 
          app-name: external-secrets-config 
          path: argocd/kustomize/overlays/rancher-master/external-secrets-config
          namespace: external-secrets
        - cluster: k3s-server 
          app-name: external-dns
          path: argocd/kustomize/overlays/k3s-server/external-dns/
          namespace: external-dns
        - cluster: rancher-master 
          app-name: homer-app-httproute
          path: argocd/kustomize/overlays/rancher-master/homer-app-httproute
          namespace: homer-app
        - cluster: rke2-cluster 
          app-name: pixiedocs-app
          path: argocd/kustomize/overlays/rke2-cluster/pixiedocs-app/
          namespace: gotenberg
        - cluster: rke2-cluster 
          app-name: neuvector-external-secret
          path: argocd/kustomize/overlays/rke2-cluster/neuvector-external-secret/
          namespace: cattle-neuvector-system
        - cluster: rke2-cluster 
          app-name: neuvector-httproute
          path: argocd/kustomize/overlays/rke2-cluster/neuvector-httproute/
          namespace: cattle-neuvector-system
        - cluster: rke2-cluster 
          app-name: neuvector-configmaps
          path: argocd/kustomize/overlays/rke2-cluster/neuvector-configmaps/
          namespace: cattle-neuvector-system
  template:
    metadata:
      name: '{{cluster}}-{{app-name}}'
      namespace: argo
    spec:
      project: default
      sources:
        - repoURL: https://github.com/rajeshkio/home-lab-setup.git
          targetRevision: HEAD
          path: 'argocd/kustomize/overlays/{{cluster}}/{{app-name}}'
      destination:
        name: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        automated:
          prune: true
          selfHeal: true
