
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: manifest-apps
  namespace: argo
spec:
  generators:
  - list:
      elements:
#        - cluster: rancher-master 
#          app-name: vault-cert-sync-job
#          path: argocd/kustomize/overlays/rancher-master/vault-cert-sync-job/
#          namespace: cert-manager
#
#        - cluster: rancher-master
#          app-name: vault-configs
#          path: argocd/kustomize/overlays/rancher-master/vault-config/
#          namespace: vault  

        - cluster: rancher-master 
          app-name: external-dns
          path: argocd/kustomize/overlays/rancher-master/external-dns/
          namespace: external-dns

        - cluster: rancher-master 
          app-name: external-secrets-config 
          path: argocd/kustomize/overlays/rancher-master/external-secrets-config
          namespace: external-secrets

        - cluster: rancher-master 
          app-name: rancher-httproute
          path: argocd/kustomize/overlays/rancher-master/rancher-httproute
          namespace: cattle-system

        - cluster: rancher-master 
          app-name: cert-manager-config 
          path: argocd/kustomize/overlays/rancher-master/cert-manager-config
          namespace: cert-manager

        - cluster: rancher-master 
          app-name: homer-app-httproute
          path: argocd/kustomize/overlays/rancher-master/homer-app-httproute
          namespace: homer-app

        - cluster: rancher-master 
          app-name: gateway 
          path: argocd/kustomize/overlays/rancher-master/gateway/
          namespace: common-gateway

        - cluster: k3s-cluster 
          app-name: pixiedocs-app
          path: argocd/kustomize/overlays/k3s-cluster/pixiedocs-app/
          namespace: gotenberg

        - cluster: k3s-cluster 
          app-name: neuvector-external-secret
          path: argocd/kustomize/overlays/k3s-cluster/neuvector-external-secret/
          namespace: cattle-neuvector-system

        - cluster: k3s-cluster 
          app-name: neuvector-httproute
          path: argocd/kustomize/overlays/k3s-cluster/neuvector-httproute/
          namespace: cattle-neuvector-system

        - cluster: k3s-cluster 
          app-name: neuvector-configmaps
          path: argocd/kustomize/overlays/k3s-cluster/neuvector-configmaps/
          namespace: cattle-neuvector-system

        - cluster: k3s-cluster 
          app-name: external-dns
          path: argocd/kustomize/overlays/k3s-cluster/external-dns/
          namespace: external-dns

        - cluster: k3s-cluster 
          app-name: rajesh-tls-external-secret 
          path: argocd/kustomize/overlays/k3s-cluster/rajesh-tls-external-secret/
          namespace: certificate-ns

        - cluster: k3s-cluster 
          app-name: external-secrets-config 
          path: argocd/kustomize/overlays/k3s-cluster/external-secrets-config/
          namespace: certificate-ns

        - cluster: k3s-cluster 
          app-name: gateway 
          path: argocd/kustomize/overlays/k3s-cluster/gateway/
          namespace: common-gateway

        - cluster: k3s-cluster 
          app-name: kiali-httproute 
          path: argocd/kustomize/overlays/k3s-cluster/kiali-httproute
          namespace: istio-system

        - cluster: k3s-cluster 
          app-name: istio-config 
          path: argocd/kustomize/overlays/k3s-cluster/istio-config
          namespace: istio-system

        - cluster: asus-cluster 
          app-name: external-dns
          path: argocd/kustomize/overlays/asus-cluster/external-dns/
          namespace: external-dns

        - cluster: asus-cluster 
          app-name: rajesh-tls-external-secret 
          path: argocd/kustomize/overlays/asus-cluster/rajesh-tls-external-secret/
          namespace: certificate-ns

        - cluster: asus-cluster 
          app-name: external-secrets-config 
          path: argocd/kustomize/overlays/asus-cluster/external-secrets-config/
          namespace: certificate-ns

        - cluster: asus-cluster 
          app-name: argocd-server-tls 
          path: argocd/kustomize/overlays/asus-cluster/argocd-server-tls/
          namespace: argo

  template:
    metadata:
      name: '{{cluster}}-{{app-name}}'
      namespace: argo
    spec:
      project: default
      sources:
        - repoURL: https://github.com/rajeshkio/home-lab-setup.git
          targetRevision: HEAD
          path: 'argocd/kustomize/overlays/{{cluster}}/{{app-name}}'
      destination:
        name: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        automated:
          prune: true
          selfHeal: true
