apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: neuvector-tls
  namespace: cattle-neuvector-system
spec:
  host: neuvector-service-webui.cattle-neuvector-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true # Important for self-signed certs
      sni: neuvector-service-webui.cattle-neuvector-system.svc.cluster.local
    portLevelSettings:
    - port:
        number: 8443
      tls:
        mode: SIMPLE
        insecureSkipVerify: true
