apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: neuvector-httproute
  namespace: cattle-neuvector-system
spec:
  hostnames:
  - "nv.rajesh-kumar.in"
  parentRefs:
  - name: common-server-gateway-istio 
    namespace: common-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: neuvector-service-webui 
      port: 8443
