---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: neuvector-httproute
  namespace: cattle-neuvector-system
spec:
  hostnames:
  - "nv-rke2.rajesh-kumar.in"
  parentRefs:
  - name: rke2-server-gateway 
    namespace: istio-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: neuvector-service-webui 
      port: 8443
